### ISSUE TITLE
using model as prediction 

### ISSUE THREAD

**Issue by kyle8581** [wtomin/Multitask-Emotion-Recognition-with-Incomplete-Labels#10]
Hello,
I read the description about using your pre-trained model. And I tried following description but I failed. Because I don't have 
resnet50_ferplus_dag.py

the exact error message was
 FileNotFoundError: [Errno 2] No such file or directory: 'models/fer+/resnet50_ferplus_dag.py'

I checked you added as pretrained model link, but there were only .pth and pkls.
Can you give me some advice?

**Comment by wtomin** [comment]
There are two ways to solve this problem:
(1) you can rewrite the function [_init_create_networks](https://github.com/wtomin/Multitask-Emotion-Recognition-with-Incomplete-Labels/blob/ea7f3f2dad85d0c89b7fbd906e17d21f6f91315d/run_pretrained_model.py#L260) to skip loading pretrained ResNet50 model, since our pretrained model will be loaded anyway(in main function, 597 line);
(2) In the directory ` pytorch-benchmarks/models/`, there are three folders, named `fer`, `fer+` and `sfew`. They contain the model weights (`.pth` files) and model definition file (`.py`). These were downloaded from this [link](https://www.robots.ox.ac.uk/~albanie/pytorch-models.html). You can try to download them to required location.

**Comment by kyle8581** [comment]
I really appreciate your reply. The problem is solved by adding the files from pytorch-benchmarks. 
Thanks!
