### ISSUE TITLE
Creating aligned images of ExpW dataset problem

### ISSUE THREAD

**Issue by tghim** [wtomin/Multitask-Emotion-Recognition-with-Incomplete-Labels#14]
Thank you so much for your sharing.
I have a question about creating aligned images of ExpW dataset.
In the Expw dataset, several people appear at the same time in some images. Therefore, there are cases in which there are multiple labels although the name is the same in the annotation file. And when I looked at 'create_annotation_file/ExpW/create_annotations.py', I found that in this case, I could only get an image of one out of several people. So the image directory only has 68,096 images, while the number of instances of the annotation file is 91,793. I wonder if the result of the paper is the result of applying it as it is or the result of modifying it.

**Comment by wtomin** [comment]
Sorry for my late reply. 
After you mentioned this mismatch of number of instances in the annotation file and the number of cropped images, I realized that the `label.lst` file have repetitive image names, for example, `angry_asian_330.jpg` appeared twice in `label.lst`. It turned out the `create_annotations.py` led to errors, because the cropped faces did not align with the instances in the annotation file.

I will correct it in near future. Thanks for informing me.

**Comment by tghim** [comment]
Thank you for your reply.
