### ISSUE TITLE
About Datasets

### ISSUE THREAD

**Issue by Levi0223** [wtomin/Multitask-Emotion-Recognition-with-Incomplete-Labels#15]
I know it's a little bit stupid, but could you please list the structure of the whole three datasets or the folder where you put your data.

**Comment by wtomin** [comment]
Sorry for my late reply. 
Regarding the datasets and their folders, they are actually not that important. Since I created annotation file `annotations.pkl`. 
The `annotations.pkl` is a dictionary, where the key names recursively indicate the partitions, from subsets (e.g., EXPR_Set) to train/val set, then to the video names. Finally, each video name corresponds to a dataframe. The dataframe will give the path and emotion labels of each frame in this video. 

If you are  indeed interested in the datasets and their folders, I refer you to the `annotations.pkl` in this [link](https://hkustconnect-my.sharepoint.com/:f:/g/personal/ddeng_connect_ust_hk/EnX91m9VSHlFobaIag82W_8B3YRkir97H1QmiUlkZu1zAw?e=LGgDNE) (it is the same link in the readme.md). You can load it using `pickle` module. Here is an example:

```
import pickle as pkl
data = pkl.load(open('annotations.pkl', 'rb'))
df = data['EXPR_Set']['Training_Set']['325']
print(df.head())
```

It shows
```
   frames_ids  label                                               path
0           1      0  /media/Samsung/Aff-wild2-Challenge/cropped_ali...
1           2      0  /media/Samsung/Aff-wild2-Challenge/cropped_ali...
2           3      0  /media/Samsung/Aff-wild2-Challenge/cropped_ali...
3           4      0  /media/Samsung/Aff-wild2-Challenge/cropped_ali...
4           5      0  /media/Samsung/Aff-wild2-Challenge/cropped_ali...
```
You can inspect the datasets folders from the `path` column. 

I hope this has answered your question well.
