### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by kabbas570** [wtomin/Multitask-Emotion-Recognition-with-Incomplete-Labels#17]
Thank you for sharing the code:
I am running the "run_pretrained_model.py" as instructed in the readme, but every time I got the following error:
Can you advise, please?
For  python run_pretrained_model.py --image_dir (path to faces cropped and aligned by openface)--model_type CNN --batch_size 2 --eval_with_teacher --eval_with_students --save_dir (path to a folder to save results) --workers 8 --ensemble

And in the run_pretrained_model.py file, I change the path in  python run_pretrained_model.py as:
MODEL_DIR = r'C:\Multitask-Emotion-Recognition-with-Incomplete-Labels-master\pytorch-benchmarks\models'
Here in the model's folder, I made a folder with fer+ name and put resnet50_feplus_dag.py and  resnet50_feplus_dag.pth there.
And I am getting the following error:

Traceback (most recent call last):
File "run_pretrained_model.py", line 664, in
main()
File "run_pretrained_model.py", line 585, in main
assert len(path) == 1

I download their pre-trained models from 
https://hkustconnect-my.sharepoint.com/personal/ddeng_connect_ust_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fddeng%5Fconnect%5Fust%5Fhk%2FDocuments%2FFG2020%2DABAW

but it is not specified in which folder we should keep these pre-trained models, so I put them in the main directory I think I a doing something wrong here?
Thank You

**Comment by belenal** [comment]
> Thank you for sharing the code: I am running the "run_pretrained_model.py" as instructed in the readme, but every time I got the following error: Can you advise, please? For python run_pretrained_model.py --image_dir (path to faces cropped and aligned by openface)--model_type CNN --batch_size 2 --eval_with_teacher --eval_with_students --save_dir (path to a folder to save results) --workers 8 --ensemble
> 
> And in the run_pretrained_model.py file, I change the path in python run_pretrained_model.py as: MODEL_DIR = r'C:\Multitask-Emotion-Recognition-with-Incomplete-Labels-master\pytorch-benchmarks\models' Here in the model's folder, I made a folder with fer+ name and put resnet50_feplus_dag.py and resnet50_feplus_dag.pth there. And I am getting the following error:
> 
> Traceback (most recent call last): File "run_pretrained_model.py", line 664, in main() File "run_pretrained_model.py", line 585, in main assert len(path) == 1
> 
> I download their pre-trained models from https://hkustconnect-my.sharepoint.com/personal/ddeng_connect_ust_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fddeng%5Fconnect%5Fust%5Fhk%2FDocuments%2FFG2020%2DABAW
> 
> but it is not specified in which folder we should keep these pre-trained models, so I put them in the main directory I think I a doing something wrong here? Thank You

Hello! I am trying to do the same, but where did you get from the resnet50_feplus_dag.py and resnet50_feplus_dag.pth ? I dont find them

**Comment by kabbas570** [comment]
Hello @belenal ,

Yes, I have to debug the code and found that the teacher-students weights should be saved in the main folder of Multitask-CNN or Multitask-CNN-RNN.
The two files can be downloaded from here.
https://www.robots.ox.ac.uk/~albanie/models/pytorch-mcn/resnet50_ferplus_dag.pth
https://www.robots.ox.ac.uk/~albanie/models/pytorch-mcn/resnet50_pt_mcn.py

Good Luck with your research.

**Comment by belenal** [comment]
Thank you so much!

**Comment by belenal** [comment]
Hello again!
Were you able to do it like this? I am having size problems between wights and bias and the checkpoints.

Thanks!

**Comment by kabbas570** [comment]
Hello @belenal ,
What problem you are exactly facing?
I was successful to run their pre-trained.py file.
download the student's and teachers' models' weights from here.

https://hkustconnect-my.sharepoint.com/personal/ddeng_connect_ust_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fddeng%5Fconnect%5Fust%5Fhk%2FDocuments%2FFG2020%2DABAW

**Comment by wtomin** [comment]
@belenal Sorry for my late reply. I think [kabbas570](https://github.com/kabbas570) is correct. The two files can be downloaded from:
https://www.robots.ox.ac.uk/~albanie/models/pytorch-mcn/resnet50_ferplus_dag.pth
https://www.robots.ox.ac.uk/~albanie/models/pytorch-mcn/resnet50_pt_mcn.py

However, I notice that the first link was invalid probably because Albanie has removed this file from the server.  I have created a shared link where all pretrained checkpoints on FER, FER+ and SFEW can be accessed. This is the [link](https://hkustconnect-my.sharepoint.com/:f:/g/personal/ddeng_connect_ust_hk/ElE4ifQSxLBCgtfQLvgE5Z8B8wGo-SpoUJc-So_3FruMcg?e=LL3u6V). You can download all folders and save them under `pytorch_benchmarks/models/`. This can solve your first problem about resnet50_ferplus_dag. 

About where to put our pretrained model on the Aff-wild2 dataset, you can download `Multitask-CNN` and `Multitask-CNN-RNN` directories from [here](https://hkustconnect-my.sharepoint.com/personal/ddeng_connect_ust_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fddeng%5Fconnect%5Fust%5Fhk%2FDocuments%2FFG2020%2DABAW). You can put the two folders in the same directory as the `run_pretrained_model.py`
