### ISSUE TITLE
pretrained imagenet does not work

### ISSUE THREAD

**Issue by Atik16209** [wtomin/Multitask-Emotion-Recognition-with-Incomplete-Labels#20]
Hello!

I was trying to run the run the example.py script in the api folder but ran into following issues:

1)http://www.robots.ox.ac.uk/~albanie/models/pytorch-mcn/resnet50_ferplus_dag.py link does not work so it is impossible to use this model. Is it possible for you to upload it again?

2)I also tried to use pretrained imagenet instead of ferplus. To do this I changed the __OPT variable in config.py into the following:
__OPT = {"AU_label_size":8 ,
       "EXPR_label_size":7,
       "VA_label_size":2,
       "digitize_num": 20,
       "hidden_size": 128,
       "image_size": 112,
       "tasks": ['EXPR','AU','VA'],
       "pretrained_dataset": 'imagenet'}
       
    However, I get a following error when loading the the pretrained models:
RuntimeError: Error(s) in loading state_dict for Seq_Model:
	Missing key(s) in state_dict: "backbone.backbone.model.conv1.weight", "backbone.backbone.model.bn1.weight",... (some weights are missing)

Perhaps, I am missing something and should change the config more.

I would be grateful if you could help me run the models.

Kind regards
Atilla

**Comment by wtomin** [comment]
Hi! I suggest you to try the ferplus pretrained weights before you try to solve the state dictionary mismatch problem with the imagenet pretrained weigths. 

I notice that this http://www.robots.ox.ac.uk/~albanie/models/pytorch-mcn/resnet50_ferplus_dag.py does not work, probably because the author Albanie has removed the files from the server. I created a link to all pretrained weights on FER, FERPlus, and SFEW. 

https://hkustconnect-my.sharepoint.com/:f:/g/personal/ddeng_connect_ust_hk/ElE4ifQSxLBCgtfQLvgE5Z8B8wGo-SpoUJc-So_3FruMcg?e=LL3u6V

You can download all folders and put them under `pytorch_benchmarks/models/`. 

Then you can try to run `run_example.py`. This should solve the pretrained resnet50 loading problem.

**Comment by Atik16209** [comment]
Thank you, fer+ works.
