### ISSUE TITLE
i only want to get the predicted VA value,how to do?

### ISSUE THREAD

**Issue by LeiiY** [wtomin/Multitask-Emotion-Recognition-with-Incomplete-Labels#3]
hi,i just pay attention to the VA，please tell me if i should download all the file(Aff-wild2、AFEW-VA，DISFA and ExpW) and start trainning？

**Comment by wtomin** [comment]
Since our solution is a multitask solution, if you want to replicate our results, downloading all these datasets is necessary.

If you only want to get the VA estimates, you do not need to train the whole thing. Please refer to our section: [how-to-implement-our-model-on-your-data ](https://github.com/wtomin/Multitask-Emotion-Recognition-with-Incomplete-Labels#how-to-implement-our-model-on-your-data)
