### ISSUE TITLE
Is there any skipped frames within a sequence of video frames? 

### ISSUE THREAD

**Issue by ORlGlN** [wtomin/Multitask-Emotion-Recognition-with-Incomplete-Labels#9]
Would you mind to provide some details whether every frames are used for each sequence of video or how many frames were skipped during training/inference?

**Comment by wtomin** [comment]
Before merging the Aff-wild2 dataset with external datasets, we tried to make the Aff-wild2 dataset have (approximately) the same number of frames as the external dataset, by downsampling the Aff-wild2 dataset. Details are mentioned in the paper. Because Aff-wild2 dataset is a video dataset, we think downsampling won't reduce too much information.
